# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a2d6b0febeb24f6bba590dcfb235a18232a08d42280cda0b62a56d763806cb47e50c1819d2321b3415765fb35137de084b944759faf6ce9b69065fc8be908b1

test:
  secret_key_base: 21127d8bb9fa673d2b549d753acfa44fb914f8c40739e9e2b7c4663f733b9a945858c9ddbb8b2312c22eea6f5dd6581d217a5232fb3d6c21ca8156d74b1e3a63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
